# ***Pertemuan 3***


## ***Missing Values***

***Import Library***

In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

***Import Dataset***

In [2]:
dataset=pd.read_csv('Olympics2024.csv')
x=dataset.iloc[:, :].values
y=dataset.iloc[:, -1].values

In [3]:
print(x)

[[1 'United States' 'US' 40.0 44.0 42 126]
 [2 'China' 'CHN' 40.0 27.0 24 91]
 [3 'Japan' 'JPN' 20.0 12.0 13 45]
 [4 'Australia' 'AUS' 18.0 19.0 16 53]
 [5 'France' 'FRA' 16.0 26.0 22 64]
 [6 'Netherlands' 'NED' 15.0 7.0 12 34]
 [7 'Great Britain' 'GBG' 14.0 22.0 29 65]
 [8 'South Korea' 'KOR' 13.0 9.0 10 32]
 [9 'Italy' 'ITA' 12.0 13.0 15 40]
 [10 'Germany' 'GER' 12.0 13.0 8 33]
 [11 'New Zealand' 'NZ' 10.0 7.0 3 20]
 [12 'Canada' 'CAN' 9.0 7.0 11 27]
 [13 'Uzbekistan' 'UZB' 8.0 2.0 3 13]
 [14 'Hungary' 'HUN' 6.0 7.0 6 19]
 [15 'Spain' 'SPA' 5.0 4.0 9 18]
 [16 'Sweden' 'SWE' 4.0 4.0 3 11]
 [17 'Kenya' 'KEN' 4.0 2.0 5 11]
 [18 'Norway' 'NOR' 4.0 1.0 3 8]
 [19 'Ireland' 'IRE' 4.0 0.0 3 7]
 [20 'Brazil' 'BRZ' 3.0 7.0 10 20]
 [21 'Iran' 'IRN' 3.0 6.0 3 12]
 [22 'Ukraine' 'UKR' 3.0 5.0 4 12]
 [23 'Romania' 'ROM' 3.0 4.0 2 9]
 [24 'Georgia' 'GEO' 3.0 3.0 1 7]
 [25 'Belgium' 'BEL' 3.0 1.0 6 10]
 [26 'Bulgaria' 'BUL' 3.0 1.0 3 7]
 [27 'Serbia' 'SER' 3.0 nan 1 5]
 [28 'Czech Republic' 'CZE' 3.

In [4]:
print(y)

[126  91  45  53  64  34  65  32  40  33  20  27  13  19  18  11  11   8
   7  20  12  12   9   7  10   7   5   5   9   7   7   9   4   3   7   5
   4   4   3   3   7  10   7   6   6   6   4   8   5   4   8   3   3   3
   2   2   2   2   3   2   2   1   1   8   5   4   4   6   6   4   6   4
   2   1   1   1   1   1   3   2   2   2   2   1   1   1   1   1   1   1
   1]


In [5]:
print(dataset.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 91 entries, 0 to 90
Data columns (total 7 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   Rank          91 non-null     int64  
 1   Country       91 non-null     object 
 2   Country Code  91 non-null     object 
 3   Gold          90 non-null     float64
 4   Silver        89 non-null     float64
 5   Bronze        91 non-null     int64  
 6   Total         91 non-null     int64  
dtypes: float64(2), int64(3), object(2)
memory usage: 5.1+ KB
None


***Menghilangkan Missing Value***


In [6]:
# periksa nilai yang hilang di setiap kolom
print(dataset.isnull().sum())

Rank            0
Country         0
Country Code    0
Gold            1
Silver          2
Bronze          0
Total           0
dtype: int64


In [7]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan, strategy='most_frequent')
imputer.fit(x[:, 3:4])
x[:, 3:4] = imputer.transform(x[:, 3:4])

In [8]:
print(x)

[[1 'United States' 'US' 40.0 44.0 42 126]
 [2 'China' 'CHN' 40.0 27.0 24 91]
 [3 'Japan' 'JPN' 20.0 12.0 13 45]
 [4 'Australia' 'AUS' 18.0 19.0 16 53]
 [5 'France' 'FRA' 16.0 26.0 22 64]
 [6 'Netherlands' 'NED' 15.0 7.0 12 34]
 [7 'Great Britain' 'GBG' 14.0 22.0 29 65]
 [8 'South Korea' 'KOR' 13.0 9.0 10 32]
 [9 'Italy' 'ITA' 12.0 13.0 15 40]
 [10 'Germany' 'GER' 12.0 13.0 8 33]
 [11 'New Zealand' 'NZ' 10.0 7.0 3 20]
 [12 'Canada' 'CAN' 9.0 7.0 11 27]
 [13 'Uzbekistan' 'UZB' 8.0 2.0 3 13]
 [14 'Hungary' 'HUN' 6.0 7.0 6 19]
 [15 'Spain' 'SPA' 5.0 4.0 9 18]
 [16 'Sweden' 'SWE' 4.0 4.0 3 11]
 [17 'Kenya' 'KEN' 4.0 2.0 5 11]
 [18 'Norway' 'NOR' 4.0 1.0 3 8]
 [19 'Ireland' 'IRE' 4.0 0.0 3 7]
 [20 'Brazil' 'BRZ' 3.0 7.0 10 20]
 [21 'Iran' 'IRN' 3.0 6.0 3 12]
 [22 'Ukraine' 'UKR' 3.0 5.0 4 12]
 [23 'Romania' 'ROM' 3.0 4.0 2 9]
 [24 'Georgia' 'GEO' 3.0 3.0 1 7]
 [25 'Belgium' 'BEL' 3.0 1.0 6 10]
 [26 'Bulgaria' 'BUL' 3.0 1.0 3 7]
 [27 'Serbia' 'SER' 3.0 nan 1 5]
 [28 'Czech Republic' 'CZE' 3.

***Encoding Data Kategori (Atribut)***

In [9]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [1,2])], remainder='passthrough')
x = np.array(ct.fit_transform(x))

In [10]:
print(x)

  (0, 88)	1.0
  (0, 179)	1.0
  (0, 182)	1.0
  (0, 183)	40.0
  (0, 184)	44.0
  (0, 185)	42.0
  (0, 186)	126.0
  (1, 15)	1.0
  (1, 105)	1.0
  (1, 182)	2.0
  (1, 183)	40.0
  (1, 184)	27.0
  (1, 185)	24.0
  (1, 186)	91.0
  (2, 46)	1.0
  (2, 138)	1.0
  (2, 182)	3.0
  (2, 183)	20.0
  (2, 184)	12.0
  (2, 185)	13.0
  (2, 186)	45.0
  (3, 4)	1.0
  (3, 95)	1.0
  (3, 182)	4.0
  (3, 183)	18.0
  :	:
  (86, 64)	1.0
  (86, 155)	1.0
  (86, 182)	84.0
  (86, 185)	1.0
  (86, 186)	1.0
  (87, 69)	1.0
  (87, 162)	1.0
  (87, 182)	84.0
  (87, 185)	1.0
  (87, 186)	1.0
  (88, 73)	1.0
  (88, 166)	1.0
  (88, 182)	84.0
  (88, 185)	1.0
  (88, 186)	1.0
  (89, 74)	1.0
  (89, 169)	1.0
  (89, 182)	84.0
  (89, 185)	1.0
  (89, 186)	1.0
  (90, 90)	1.0
  (90, 181)	1.0
  (90, 182)	84.0
  (90, 185)	1.0
  (90, 186)	1.0


***Encoding data kategori (Label)***

In [11]:
from sklearn.preprocessing import LabelEncoder
# Encoding target "Purchased" menggunakan LabelEncoder
le = LabelEncoder()
y = le.fit_transform(y)

In [12]:
print(y)

[26 25 21 22 23 19 24 17 20 18 15 16 12 14 13 10 10  7  6 15 11 11  8  6
  9  6  4  4  8  6  6  8  3  2  6  4  3  3  2  2  6  9  6  5  5  5  3  7
  4  3  7  2  2  2  1  1  1  1  2  1  1  0  0  7  4  3  3  5  5  3  5  3
  1  0  0  0  0  0  2  1  1  1  1  0  0  0  0  0  0  0  0]


***Membagi dataset ke dalam training set dan test set***

In [13]:
from sklearn.model_selection import train_test_split

# Asumsi x adalah singleton array yang mengandung sparse matrix
# Akses sparse matrix dari dalam array tersebut
x_sparse = x.item() if isinstance(x, np.ndarray) else x  # Ambil sparse matrix

# Jika x adalah sparse matrix, konversi ke dense array
if hasattr(x_sparse, 'toarray'):
    x_dense = x_sparse.toarray()  # Konversi sparse matrix ke dense array

# Split data (x_dense: fitur, y: target) ke dalam train dan test set
x_train, x_test, y_train, y_test = train_test_split(x_dense, y, test_size=0.2, random_state=42)

Diperlukan akses sparse matrix dan konversi ke dense array dahulu sebelum memasukkan test size. Code sebelumnya bisa eror karena objek x kita tampaknya tidak secara langsung merupakan sparse matrix atau dense array, melainkan sebuah singleton array yang mengandung sparse matrix. Ini berarti kita perlu mengambil sparse matrix dari objek tersebut terlebih dahulu.

In [15]:
print(x_train)

[[ 0.  0.  0. ...  3.  2.  5.]
 [ 0.  0.  0. ...  4.  3. 11.]
 [ 0.  0.  0. ...  2.  4.  6.]
 ...
 [ 0.  0.  0. ...  1.  3.  4.]
 [ 0.  0.  0. ...  4.  9. 18.]
 [ 0.  0.  1. ...  1.  1.  3.]]


In [16]:
print(x_test)

[[0. 0. 0. ... 5. 1. 7.]
 [0. 0. 0. ... 4. 2. 9.]
 [0. 0. 0. ... 1. 0. 2.]
 ...
 [0. 0. 0. ... 0. 3. 7.]
 [0. 0. 0. ... 2. 5. 9.]
 [0. 0. 0. ... 2. 1. 4.]]


In [17]:
print (y_train)

[ 4 10  5  0  6  2 16  3  5  8  0 18  3 19  6  7 10  5  6 17  1  4 15  0
  6  2 14  9 22  7  2 20  1 24  0  3  1  1  0  1  5  7  3  0  0  0  0  9
  2  4  1  1  3  0  1  7  2  3  6 25  2 11 21  6  0  0  1 11  1  3 13  2]


In [18]:
print(y_test)

[ 6  8  1  0 26  4  2  3 15  5  0  4  5  0 12 23  6  8  3]


## **Feature Scaling**

In [20]:
from sklearn.preprocessing import StandardScaler
# Menerapkan standarisasi pada fitur numerik (mulai dari kolom ke-4)
scaler = StandardScaler()
x_train[:, 3:] = scaler.fit_transform(x_train[:, 3:])
x_test[:, 3:] = scaler.transform(x_test[:,  3:])

In [21]:
print (x_train)

[[ 0.          0.          0.         ... -0.0330929  -0.37693364
  -0.33812279]
 [ 0.          0.          0.         ...  0.16270678 -0.18714887
   0.04029443]
 [ 0.          0.          0.         ... -0.22889259  0.0026359
  -0.27505325]
 ...
 [ 0.          0.          0.         ... -0.42469227 -0.18714887
  -0.40119232]
 [ 0.          0.          0.         ...  0.16270678  0.95155975
   0.48178117]
 [ 0.          0.          1.         ... -0.42469227 -0.56671841
  -0.46426186]]


In [22]:
print(y_train)

[ 4 10  5  0  6  2 16  3  5  8  0 18  3 19  6  7 10  5  6 17  1  4 15  0
  6  2 14  9 22  7  2 20  1 24  0  3  1  1  0  1  5  7  3  0  0  0  0  9
  2  4  1  1  3  0  1  7  2  3  6 25  2 11 21  6  0  0  1 11  1  3 13  2]
